# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoCSV
                                 A QGIS plugin
 This plugin creates a vector layer from loaded csv-file to make it available to edit
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-29
        copyright            : (C) 2022 by Andrey Kolomatskiy
        email                : andrey@kolomatskiy.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoCSV class from file GeoCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GeoCSV import GeoCSV
    return GeoCSV(iface)
